### PR TITLE
IdTable was not accessable from mail.messageThread() because of closure scope limitations. 

### PR DESCRIPTION
**Pull request by gergely-ujvari**
Added getIdTable() function to access it.

I've added the simple tests under the demonstration/ folder.
Run the idTable_test.js for the original version and you'll see that the idTable is {} in both cases.
Run the idTable_test_new.js for this version I pushed here and you'll see that the getIdTable() function returns the messages.

### CODE REVIEW

**Comment by tilgovi** [comment]
Could you edit the existing test file and add a test that fails without this change but passes with?

**Comment by tilgovi** [comment]
We could also do this without any breaking changes by making idTable a getter function. If you do that, and move your idTable_test.js code into jwz_test and add assertions, it will be a test which demonstrates the change neatly.

**Comment by gergely-ujvari** [comment]
I made some experience with this and couldn't change it that way that doesn't break anything.
Getter function: `getIdTable = function() { return(idTable); }`
Return part:

```
        thread: thread,
        idTable: getIdTable
```

Now when I call `idTable()` it works but it has broken the previous way which was simply `idTable` 
If I can the return part to like this:

```
        thread: thread,
        idTable: getIdTable()
```

Than the `idTable` is valid but gives back an empty structure again. (So the visibility error came back)

**Comment by tilgovi** [comment]
`Object.defineProperty(..., 'idTable', { ... get: function () { return idTable } ... }`

or with getter syntax

``` javascript
{
  ...
  get idTable: function () { return idTable }
  ...
}
```

**Comment by tilgovi** [comment]
https://developer.mozilla.org/en-US/docs/JavaScript/Guide/Working_with_Objects?redirectlocale=en-US&redirectslug=Core_JavaScript_1.5_Guide%2FWorking_with_Objects#Defining_getters_and_setters

**Comment by gergely-ujvari** [comment]
Oh, yeah. Seems my knowledge about getters was a bit outdated.
Changed it that way and now it works.
Also added a test case in jwz_test.js and removed the demonstration files.
https://github.com/gergely-ujvari/conversationThreading-js/commit/d332901f6b490c4bcec6fb2a321ed584b0e053df

**Pull request closed without merging**
